name: 'R2 Upload'
description: 'Upload a file to CloudFlare R2 bucket'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  endpoint:
    description: 'R2 API endpoint'
    required: true
  access_key_id:
    description: 'R2 Access Key ID'
    required: true
  secret_access_key:
    description: 'R2 Access Key'
    required: true
  bucket:
    description: 'Bucket name'
    required: true
  file:
    description: 'File you would like to upload'
    required: true
  destination:
    description: 'R2 end filepath (defaults to the name of the file)'
    required: false
    default: ""
runs:
  using: 'node16'
  main: 'index.js'
